# Generated by Django 5.1.6 on 2025-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
