# Generated by Django 5.1.6 on 2025-03-12 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 4, 13, 3, 964407, tzinfo=datetime.timezone.utc)),
        ),
    ]
