# Generated by Django 5.1.6 on 2025-03-04 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 5, 5, 47, 273990, tzinfo=datetime.timezone.utc)),
        ),
    ]
