# Generated by Django 5.1.6 on 2025-03-13 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeworks', '0002_alter_homeworktaskmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 20, 27, 4, 266077, tzinfo=datetime.timezone.utc)),
        ),
    ]
