# Generated by Django 5.1.6 on 2025-03-13 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeworks', '0004_alter_homeworktaskmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 21, 36, 16, 655854, tzinfo=datetime.timezone.utc)),
        ),
    ]
