# Generated by Django 5.1.6 on 2025-03-13 13:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeworks', '0005_alter_homeworktaskmodel_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmissionmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='app_homeworks.homeworktaskmodel'),
        ),
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 1, 32, 46, 71561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
