# Generated by Django 5.1.6 on 2025-03-13 16:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeworks', '0006_alter_homeworksubmissionmodel_task_and_more'),
        ('app_lessons', '0005_rename_media_lessonmodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmissionmodel',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='app_homeworks.homeworktaskmodel'),
        ),
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 4, 27, 10, 36989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_task', to='app_lessons.lessonmodel'),
        ),
    ]
