# Generated by Django 5.1.6 on 2025-03-14 09:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groups', '0002_groupmodel_time'),
        ('app_homeworks', '0007_alter_homeworksubmissionmodel_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworktaskmodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='app_groups.groupmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworktaskmodel',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 21, 8, 22, 404941, tzinfo=datetime.timezone.utc)),
        ),
    ]
