# Generated by Django 5.1.6 on 2025-03-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groups', '0001_initial'),
        ('app_users', '0002_customusermodel_group_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='app_groups.groupmodel'),
        ),
    ]
