# Generated by Django 5.1.6 on 2025-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
