# Generated by Django 5.1.6 on 2025-03-04 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groups', '0001_initial'),
        ('app_lessons', '0001_initial'),
        ('app_users', '0003_alter_customusermodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app_groups.groupmodel'),
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
    ]
