# Generated by Django 5.1.6 on 2025-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0002_lessonmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
    ]
