# Generated by Django 5.1.6 on 2025-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0003_lessonmodel_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='media',
            field=models.FileField(null=True, upload_to='lessons/'),
        ),
    ]
