# Generated by Django 5.1.6 on 2025-03-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lessons', '0004_lessonmodel_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonmodel',
            old_name='media',
            new_name='video',
        ),
    ]
